### ISSUE TITLE
【android】开启混淆后打开app闪退

### ISSUE THREAD

**Issue by JeauLiang** [didi/DoKit#1058]
请补充如下信息。
> 版本：dokitx:3.5.0
> 问题重现的步骤：集成后打开app
> Android 9.0，手机品牌：sony xzp

> 报错信息如下：
```
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.lang.Iterable.iterator()' on a null object reference
        at com.didichuxing.doraemonkit.kit.toolpanel.ToolPanelUtil$Companion.a(ToolPanelUtil.kt:68)
        at com.didichuxing.doraemonkit.DoKitReal$addInnerKit$2.invokeSuspend(DoKitReal.kt:211)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.b(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.a(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.f(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by FeanCheng** [comment]
-keep class com.didichuxing.doraemonkit.**{*;}
规则里加个 keep

**Comment by FeanCheng** [comment]
> -keep class com.didichuxing.doraemonkit.**{*;}
> 规则里加个 keep

@JeauLiang

**Comment by JeauLiang** [comment]
> -keep class com.didichuxing.doraemonkit.**{*;} 规则里加个 keep

好的，谢谢
