### ISSUE TITLE
【Android】- 没有适配Gradle最新版7.5.1

### ISSUE THREAD

**Issue by yswheye** [didi/DoKit#1073]
getGlobalScope应该是gradle7.0中的方法，7.5已经没有了。

Caused by: java.lang.NoSuchMethodError: 'com.android.build.gradle.internal.scope.GlobalScope com.android.build.api.component.impl.ComponentImpl.getGlobalScope()'
        at com.didiglobal.booster.android.gradle.v7_0.V70.getGlobalScope(V70.kt:117)
        at com.didiglobal.booster.android.gradle.v7_0.V70.getProject(V70.kt:75)
        at com.didiglobal.booster.gradle.BaseVariantKt.getProject(BaseVariant.kt:25)
        at com.didichuxing.doraemonkit.plugin.processor.DoKitPluginConfigProcessor$process$$inlined$let$lambda$1.execute(DoKitPluginConfigProcessor.kt:155)
        at com.didichuxing.doraemonkit.plugin.processor.DoKitPluginConfigProcessor$process$$inlined$let$lambda$1.execute(DoKitPluginConfigProcessor.kt:31)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:770)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:743)
        at org.gradle.api.internal.tasks.execution.TaskExecution$2.run(TaskExecution.java:239)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)

**Comment by ResetYtb** [comment]
> 

你最后怎么处理的呢？

**Comment by caldremch** [comment]
buildscript {
    dependencies {
        classpath("io.github.didi.dokit:dokitx-plugin:3.7.1")
        classpath("com.didiglobal.booster:booster-gradle-plugin:4.15.0")
    }
}

我这样配置可以

**Comment by zZfd** [comment]
> buildscript { dependencies { classpath("io.github.didi.dokit:dokitx-plugin:3.7.1") classpath("com.didiglobal.booster:booster-gradle-plugin:4.15.0") } }
> 
> 我这样配置可以

我这样配置之后，booster出错了。。https://github.com/didi/booster/issues/330

**Comment by est7** [comment]
@caldremch 你gradle和agp分别是什么版本

**Comment by linxiangcheer** [comment]
> @caldremch 你gradle和agp分别是什么版本

gradle：7.3.3
agp：7.2.2

**Comment by BeyondWorlds** [comment]
gradle：7.0.2成功解决
