### ISSUE TITLE
【Android】Fluter打开WebView报错

### ISSUE THREAD

**Issue by xhjww** [didi/DoKit#1146]

**Comment by xhjww** [comment]
> 版本：3.7.11 原生Flutter混合开发项目，Flutter端打开WebView报错。 flutter: reportErrorAndLog=══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞══════════════════════ The following PlatformException was thrown: PlatformException(ClassCastException, java.lang.ClassCastException: com.didichuxing.doraemonkit.kit.h5_help.DoKitWebViewClient cannot be cast to io.flutter.plugins.webviewflutter.WebViewClientHostApiImpl$ReleasableWebViewClient, Cause: null, Stacktrace: java.lang.ClassCastException: com.didichuxing.doraemonkit.kit.h5_help.DoKitWebViewClient cannot be cast to io.flutter.plugins.webviewflutter.WebViewClientHostApiImpl$ReleasableWebViewClient at io.flutter.plugins.webviewflutter.WebViewHostApiImpl$WebViewPlatformView.setWebViewClient(WebViewHostApiImpl.java:133) at com.didichuxing.doraemonkit.aop.WebViewHook.injectNormal(WebViewHook.java:76) at com.didichuxing.doraemonkit.aop.WebViewHook.inject(WebViewHook.java:58) at io.flutter.plugins.webviewflutter.WebViewHostApiImpl.loadUrl(WebViewHostApiImpl.java:372) at io.flutter.plugins.w
